# SPDX-FileCopyrightText: 2026 SyuanTsai
# SPDX-License-Identifier: Apache-2.0
# JSON files cannot carry comments; their ownership is declared here.

version = 1

[[annotations]]
path = "catalog/source.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 SyuanTsai"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "VERSION"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 SyuanTsai"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "NOTICE"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 SyuanTsai"
SPDX-License-Identifier = "Apache-2.0"
